-- AlterTable
ALTER TABLE "availability" 
ALTER COLUMN "startDate" TYPE TIMESTAMPTZ USING DATE_TRUNC('day', "startDate" AT TIME ZONE 'UTC'),
ALTER COLUMN "endDate" TYPE TIMESTAMPTZ USING DATE_TRUNC('day', "endDate" AT TIME ZONE 'UTC');

-- AlterTable
ALTER TABLE "shift" 
ALTER COLUMN "startTime" TYPE TIMESTAMPTZ USING "startTime" AT TIME ZONE 'UTC',
ALTER COLUMN "endTime" TYPE TIMESTAMPTZ USING "endTime" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "shift_draft" 
ALTER COLUMN "startTime" TYPE TIMESTAMPTZ USING "startTime" AT TIME ZONE 'UTC',
ALTER COLUMN "endTime" TYPE TIMESTAMPTZ USING "endTime" AT TIME ZONE 'UTC';
